# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'default'

stages:
  - stage: Validate TF Code
    jobs:
    - job: Validate
      continueOnError: false
      steps:
      - script: |
          echo Validate Terraform Code with TFE remote backend
          cd k8s
          terraform init -no-color -backend-config="token=xJBnw4QmfAmbJw.atlasv1.4Alv2dxmVCV3i1A2AZgJNRDO6ep19Wq63OyRRLFpk5v7f72QzGi3JJu6Mg1DuJNh76c"
          terraform validate -no-color
        displayName: 'Validate Terraform Code'

  - stage: Review Terrafrm Plan
    jobs:
    - job: Plan
      continueOnError: false
      steps:
      - script: |
          echo Run Terraform plan with TFE remote backend
          cd k8s
          terraform init -no-color -backend-config="token=xJBnw4QmfAmbJw.atlasv1.4Alv2dxmVCV3i1A2AZgJNRDO6ep19Wq63OyRRLFpk5v7f72QzGi3JJu6Mg1DuJNh76c"
          terraform plan -no-color
        displayName: 'Run Terraform Plan'

  - stage: Apply Terraform Code
    jobs:
    - job: Apply
      continueOnError: false
      steps:
      - script: |
          echo Applying Terraform with TFE remote backend
          cd k8s
          terraform init -no-color -backend-config="token=xJBnw4QmfAmbJw.atlasv1.4Alv2dxmVCV3i1A2AZgJNRDO6ep19Wq63OyRRLFpk5v7f72QzGi3JJu6Mg1DuJNh76c"
          terraform apply -no-color
      displayName: 'Apply Terraform'
  
  - stage: Get Kubeconfig
    jobs:
    - job: kubeconfig
      continueOnError: false
      steps:
      - script: |
          echo Create kubeconfig for k8s
          cd k8s
          terraform output kube_config > azurek8s
        displayName: 'Create kubeconfig'
      
  - stage: Validate K8s cluster
    jobs:
    - job: k8s_get_nodes
      continueOnError: false
      steps:
      - script: |
          echo Get k8s cluster nodes
          cd k8s
          export KUBECONFIG=./azurek8s
          kubectl get nodes
        displayName: 'Validate k8s cluster'